sudo: required
services:
  - docker

before_install:
  - docker build -t xdcc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xdcc/react-test npm test

after_success:
  - docker build -t xdcc/multi-client ./client
  - docker build -t xdcc/multi-nginx ./nginx
  - docker build -t xdcc/multi-server ./server
  - docker build -t xdcc/multi-worker ./worker

  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push xdcc/multi-client
  - docker push xdcc/multi-nginx
  - docker push xdcc/multi-server
  - docker push xdcc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-481730389010
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic
